name: angular_anaelle
description: Anaelle
version: 0.0.1
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular: ^4.0.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2
  http: ^0.11.0            
  stream_transform: ^0.0.6

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  mockito: ^2.0.2

transformers:
- angular:
    entry_points:
    - web/main.dart
- dart_to_js_script_rewriter